FROM implem/pleasanter:codedefiner
COPY Implem.License.dll /app/Implem.CodeDefiner/Implem.License.dll

# Copy entrypoint script
COPY entrypoint-codedefiner.sh /app/entrypoint-codedefiner.sh
RUN chmod +x /app/entrypoint-codedefiner.sh

WORKDIR /app
ENTRYPOINT ["/app/entrypoint-codedefiner.sh"]
