FROM implem/pleasanter:codedefiner

# Copy entrypoint script
COPY entrypoint-codedefiner.sh /app/entrypoint-codedefiner.sh
RUN chmod +x /app/entrypoint-codedefiner.sh

WORKDIR /app
ENTRYPOINT ["/app/entrypoint-codedefiner.sh"]
